FROM python:3.10-slim

WORKDIR /home/app/web

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

# Add cron
RUN apt-get update && apt-get install -y cron && \
    echo "0 3 * * 0 cd /home/app/web && python manage.py sync_parks >> /var/log/cron.log 2>&1" > /etc/cron.d/sync_parks && \
    chmod 0644 /etc/cron.d/sync_parks && \
    crontab /etc/cron.d/sync_parks

CMD ["cron", "-f"]
