version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/home/app/web
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  npe:
  # Location to the react.js dockerfile
    build: 
      context: ./frontend
        # Name of the dockerfile
      dockerfile: Dockerfile.prod
    container_name: npe-frontend
    # environment:
    #   - VIRTUAL_HOST=npe.marshallcodes.com
    #   - VIRTUAL_PORT=8001
    #   - LETSENCRYPT_HOST=npe.marshallcodes.com
    #   - LETSENCRYPT_EMAIL=marshallheyda@gmail.com
    expose:
      - 8001
    stdin_open: true
  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./national_park_explorer/static/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - npe

volumes:
  postgres_data:
  static:
  media_volume:
