# Generated by Django 4.0.5 on 2025-10-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_explorer', '0002_alter_alert_alert_id_alter_campground_campground_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='last_updated',
            field=models.DateTimeField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='campground',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
