# Generated by Django 4.0.5 on 2025-10-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_explorer', '0003_alter_campground_cell_phone_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='campground',
            name='description',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
