# Generated by Django 4.0.5 on 2025-04-26 00:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import national_park_explorer.models


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_explorer', '0003_rename_favorites_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpxFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=national_park_explorer.models.generate_filepath, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gpx'], message='Invalid file type.')])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
