# Generated by Django 4.0.5 on 2025-05-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_explorer', '0004_gpxfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxfile',
            name='bounds',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
