# Generated by Django 4.0.5 on 2025-10-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_explorer', '0004_alter_alert_description_alter_alert_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campground',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campground',
            name='directions_overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campground',
            name='fire_stove_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campground',
            name='rv_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
