# Generated by Django 4.0.5 on 2025-10-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_explorer', '0005_alter_alert_description_alter_campground_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='park_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='campground',
            name='park_code',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='campground',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
