# Generated by Django 4.0.5 on 2025-05-07 21:39

from django.db import migrations
import gpxpy

def populate_bounds(apps, schema_editor):
    gpx_files = apps.get_model('national_park_explorer', 'GpxFile')

    for gpx_file in gpx_files.objects.all():


        with open(gpx_file.file.path, 'r', encoding='utf-8') as f:
            gpx = gpxpy.parse(f)
        
        # Initialize bounds
        min_lat = float('inf')
        max_lat = float('-inf')
        min_lon = float('inf')
        max_lon = float('-inf')

        # Iterate through all the track segments and points to find the bounds
        for track in gpx.tracks:
            for segment in track.segments:
                for point in segment.points:
                    lat, lon = point.latitude, point.longitude
                    min_lat = min(min_lat, lat)
                    max_lat = max(max_lat, lat)
                    min_lon = min(min_lon, lon)
                    max_lon = max(max_lon, lon)
        
        gpx_file.bounds = [[min_lat, min_lon], [max_lat, max_lon]]
        gpx_file.save()

class Migration(migrations.Migration):

    dependencies = [
        ('national_park_explorer', '0005_gpxfile_bounds'),
    ]

    operations = [
        migrations.RunPython(populate_bounds),
    ]
