# Generated by Django 4.0.5 on 2025-10-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_explorer', '0006_alter_alert_park_code_alter_campground_park_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='park_code',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='alert',
            name='title',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='alert',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
