# Generated by Django 4.0.5 on 2025-10-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_explorer', '0007_alter_alert_category_alter_alert_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campground',
            name='cell_phone_info',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='campground',
            name='email_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='campground',
            name='internet_info',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='campground',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='campground',
            name='park_code',
            field=models.CharField(db_index=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='campground',
            name='phone_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='campground',
            name='phone_number',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='campground',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='campground',
            name='wheelchair_access',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
