# Generated by Django 4.0.5 on 2025-05-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_explorer', '0007_gpxfile_geojson_gpxfile_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxfile',
            name='ascent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpxfile',
            name='avg_cadence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpxfile',
            name='avg_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpxfile',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpxfile',
            name='descent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpxfile',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpxfile',
            name='max_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpxfile',
            name='moving_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpxfile',
            name='timer_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpxfile',
            name='total_elapsed_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
