# Generated by Django 4.0.5 on 2025-10-10 01:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_explorer', '0008_alter_campground_cell_phone_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('park_id', models.TextField(unique=True)),
                ('park_code', models.CharField(db_index=True, max_length=100)),
                ('full_name', models.CharField(max_length=2000)),
                ('name', models.CharField(max_length=1000)),
                ('designation', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('directions_info', models.TextField(blank=True, null=True)),
                ('directions_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('weather_info', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('states', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_type', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mailing_address_line1', models.CharField(blank=True, max_length=1000, null=True)),
                ('mailing_address_line2', models.CharField(blank=True, max_length=1000, null=True)),
                ('mailing_city', models.CharField(blank=True, max_length=200, null=True)),
                ('mailing_state', models.CharField(blank=True, max_length=20, null=True)),
                ('mailing_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('activity_names', models.JSONField(blank=True, null=True)),
                ('topic_names', models.JSONField(blank=True, null=True)),
                ('entrance_fee_title', models.CharField(blank=True, max_length=500, null=True)),
                ('entrance_fee_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('entrance_fee_description', models.TextField(blank=True, null=True)),
                ('entrance_pass_title', models.CharField(blank=True, max_length=500, null=True)),
                ('entrance_pass_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('entrance_pass_description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('image_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('image_alt_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('image_caption', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='textchunk',
            name='chunk_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='textchunk',
            name='source_type',
            field=models.CharField(choices=[('alert', 'Alert'), ('campground', 'Campground'), ('park_data', 'Park_Data')], max_length=20),
        ),
    ]
