# Generated by Django 4.0.5 on 2025-05-17 19:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import national_park_explorer.models


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_explorer', '0008_gpxfile_ascent_gpxfile_avg_cadence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=national_park_explorer.models.generate_filepath, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gpx', 'fit'], message='Invalid file type.')])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('bounds', models.JSONField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('timer_time', models.IntegerField(blank=True, null=True)),
                ('total_elapsed_time', models.IntegerField(blank=True, null=True)),
                ('moving_time', models.IntegerField(blank=True, null=True)),
                ('max_speed', models.FloatField(blank=True, null=True)),
                ('ascent', models.FloatField(blank=True, null=True)),
                ('descent', models.FloatField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True)),
                ('avg_cadence', models.IntegerField(blank=True, null=True)),
                ('geojson', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='GpxFile',
        ),
    ]
