# Generated by Django 4.0.5 on 2025-05-23 01:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import national_park_explorer.models


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_explorer', '0009_useruploadedfile_delete_gpxfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sport', models.CharField(max_length=50)),
                ('bounds', models.JSONField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('total_elapsed_time', models.FloatField()),
                ('total_distance', models.FloatField(blank=True, null=True)),
                ('total_calories', models.IntegerField(blank=True, null=True)),
                ('total_ascent', models.FloatField(blank=True, null=True)),
                ('total_descent', models.FloatField(blank=True, null=True)),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True)),
                ('avg_cadence', models.IntegerField(blank=True, null=True)),
                ('geojson', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('position_lat', models.FloatField(blank=True, null=True)),
                ('position_long', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('cadence', models.IntegerField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='national_park_explorer.activity')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=national_park_explorer.models.generate_filepath, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gpx', 'fit', 'GPX', 'FIT'], message='Invalid file type.')])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('fit', 'FIT'), ('gpx', 'GPX')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parse_error', models.TextField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='national_park_explorer.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserUploadedFile',
        ),
    ]
