# Generated by Django 4.0.5 on 2025-10-10 02:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_explorer', '0009_park_data_textchunk_chunk_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textchunk',
            name='relevance_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
