# Generated by Django 4.0.5 on 2025-10-07 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_explorer', '0011_alter_uploadedfile_file_type_visited'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('parkCode', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('fullName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('directionsInfo', models.TextField(blank=True, null=True)),
                ('directionsUrl', models.URLField(blank=True, null=True)),
                ('latLong', models.CharField(blank=True, max_length=100, null=True)),
                ('states', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('weatherInfo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='avg_cadence',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='avg_heart_rate',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='bounds',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='geojson',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='total_ascent',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='total_calories',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='total_descent',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='total_distance',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='total_elapsed_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(default='Unnamed Activity', max_length=255),
        ),
        migrations.CreateModel(
            name='StandardHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday', models.CharField(max_length=100)),
                ('monday', models.CharField(max_length=100)),
                ('tuesday', models.CharField(max_length=100)),
                ('wednesday', models.CharField(max_length=100)),
                ('thursday', models.CharField(max_length=100)),
                ('friday', models.CharField(max_length=100)),
                ('saturday', models.CharField(max_length=100)),
                ('operating_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_hours', to='national_park_explorer.operatinghours')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(max_length=20)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='national_park_explorer.park')),
            ],
        ),
        migrations.CreateModel(
            name='ParkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('altText', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='park_images/')),
                ('credit', models.CharField(blank=True, max_length=255, null=True)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='national_park_explorer.park')),
            ],
        ),
        migrations.AddField(
            model_name='park',
            name='activities',
            field=models.ManyToManyField(related_name='parks', to='national_park_explorer.activity'),
        ),
        migrations.AddField(
            model_name='park',
            name='topics',
            field=models.ManyToManyField(related_name='parks', to='national_park_explorer.topic'),
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='national_park_explorer.park'),
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('multimedia_id', models.CharField(max_length=64)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='national_park_explorer.park')),
            ],
        ),
        migrations.CreateModel(
            name='Gpx_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unnamed Activity', max_length=255, null=True)),
                ('sport', models.CharField(max_length=50)),
                ('bounds', models.JSONField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('total_elapsed_time', models.FloatField()),
                ('total_distance', models.FloatField(blank=True, null=True)),
                ('total_calories', models.IntegerField(blank=True, null=True)),
                ('total_ascent', models.FloatField(blank=True, null=True)),
                ('total_descent', models.FloatField(blank=True, null=True)),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True)),
                ('avg_cadence', models.IntegerField(blank=True, null=True)),
                ('geojson', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('sunday', models.CharField(max_length=100)),
                ('monday', models.CharField(max_length=100)),
                ('tuesday', models.CharField(max_length=100)),
                ('wednesday', models.CharField(max_length=100)),
                ('thursday', models.CharField(max_length=100)),
                ('friday', models.CharField(max_length=100)),
                ('saturday', models.CharField(max_length=100)),
                ('operating_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='national_park_explorer.operatinghours')),
            ],
        ),
        migrations.CreateModel(
            name='EntrancePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_passes', to='national_park_explorer.park')),
            ],
        ),
        migrations.CreateModel(
            name='EntranceFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_fees', to='national_park_explorer.park')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAddress', models.EmailField(max_length=254)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to='national_park_explorer.park')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255, null=True)),
                ('line3', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('stateCode', models.CharField(max_length=10)),
                ('countryCode', models.CharField(max_length=10)),
                ('provinceTerritoryCode', models.CharField(blank=True, max_length=10, null=True)),
                ('postalCode', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='national_park_explorer.park')),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='national_park_explorer.gpx_activity'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='national_park_explorer.gpx_activity'),
        ),
    ]
