# Generated by Django 4.0.5 on 2025-10-07 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_explorer', '0012_operatinghours_park_topic_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gpx_activity',
            table=None,
        ),
    ]
