# Generated by Django 4.0.5 on 2025-10-07 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_explorer', '0013_alter_gpx_activity_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gpx_activity',
            table='activity',
        ),
    ]
