# Generated by Django 4.0.5 on 2025-10-08 01:51

from django.db import migrations, models
import national_park_explorer.models
import re


def extract_lat_long(apps, schema_editor):
    Park = apps.get_model('national_park_explorer', 'Park')

    for park in Park.objects.all():
        if park.latLong:
            lat_match = re.search(r'lat:([-\d.]+)', park.latLong)
            long_match = re.search(r'long:([-\d.]+)', park.latLong)

            if lat_match and long_match:
                park.latitude = float(lat_match.group(1))
                park.longitude = float(long_match.group(1))
                park.save()

class Migration(migrations.Migration):

    dependencies = [
        ('national_park_explorer', '0014_alter_gpx_activity_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkimage',
            name='image',
            field=models.ImageField(upload_to=national_park_explorer.models.park_image_upload_path),
        ),
        migrations.RunPython(extract_lat_long),
    ]
