# Generated by Django 4.0.5 on 2025-10-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_explorer', '0015_park_latitude_park_longitude_alter_parkimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
